# Generated by Django 4.0.1 on 2022-01-21 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='--', verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='MealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('ingredients', models.TextField(verbose_name='ingredients')),
                ('image', models.ImageField(upload_to='meal_image', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='price')),
                ('real_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='real_price')),
                ('discount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9, null=True, verbose_name='discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal', to='backend.categorymodel', verbose_name='category')),
            ],
            options={
                'verbose_name': 'meal',
                'verbose_name_plural': 'meal',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=15, unique=True, verbose_name='tg_id')),
                ('contact', models.CharField(default='-', max_length=13, verbose_name='contact')),
                ('lang', models.CharField(max_length=3, verbose_name='lang')),
                ('name', models.CharField(default='-', max_length=30, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='backend.commentmodel', verbose_name='feedback')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('meal', models.ManyToManyField(related_name='order', to='backend.MealModel', verbose_name='meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.usermodel', verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='backend.usermodel', verbose_name='author'),
        ),
    ]
