# Generated by Django 4.0.1 on 2022-01-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='feedback',
        ),
    ]
